인기 태그 FE
boostcampwm-2022/web06-weview pull request #282
Opened 2022-12-03 16:27 UTC by NaamuKim

# 요약

인기 태그 FE 기능을 백엔드 명세와 맞추고 ux를 높일 수 있도록
스켈레톤 ui와 약간의 애니메이션 변경을 진행하였습니다.
# 연관 이슈
- related #274 

# Pull Request 체크리스트

## TODO

- [x] 최종 결과물을 확인했는가?
- [x] 의미 있는 커밋 메시지를 작성했는가?
    - 좋은 예시) feat [FE] : 깃허브 로그인 버튼 컴포넌트 구현 (#13)
    - 나쁜 예시) feat: 로그인 구현

2022-12-03 17:24 UTC, shyuuuuni requested changes

2022-12-03 17:24 UTC, shyuuuuni commented on client/src/components/main/TagRanking/TagRanking.tsx
> +  if (rankingData.length === 0) {
이부분 코드가 궁금합니다 아래 리턴에서도 동일하게 스켈레톤 처리를 해준 것 처럼 보이는데 차이가 있나요?

2022-12-04 04:27 UTC, NaamuKim commented on client/src/components/main/TagRanking/TagRanking.tsx
> +  if (rankingData.length === 0) {
그 부분 체크를 못했네요! 
수정 커밋 포함시켰습니다!

2022-12-05 04:23 UTC, shyuuuuni approved these changes
고생하셨습니다!!

2022-12-05 04:23 UTC, merged